apiVersion: v1
kind: Secret
metadata:
  name: univora-secrets
  namespace: univora
type: Opaque
stringData:
  DB_USERNAME: "univora"
  DB_PASSWORD: "univora123"
  DB_CONNECTION: "mysql"
  APP_KEY: "base64:5zXmhZt8hTIil9MU45k8ItOVjhDwp7NjJ/y/wyO48I0="
  JWT_SECRET: "AlViVvym88NIL3PD4foOZVgVrJStfGLeT3OwIh8CiIyTIrc9J5M8vvRy8leb3pW5"
