# Generated by Django 4.2.9 on 2025-12-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_enseignants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
