# Generated by Django 4.2.9 on 2026-03-16 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_enseignants', '0002_enseignant_is_active_alter_enseignant_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'matiere', 'annee_academique')},
        ),
        migrations.AddField(
            model_name='note',
            name='note_cc1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note CC1'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_cc2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note CC2'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_sn1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note SN1'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_sn2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note SN2'),
        ),
        migrations.CreateModel(
            name='PeriodeSaisie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2024-2025', max_length=20)),
                ('section', models.CharField(choices=[('CC1', 'Contrôle Continu S1'), ('SN1', 'Session Normale S1'), ('CC2', 'Contrôle Continu S2'), ('SN2', 'Session Normale S2'), ('TOUT', 'Tout activer (Rattrapage)')], max_length=10)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ouvert_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_creees', to='app_enseignants.administrateur')),
            ],
            options={
                'verbose_name': 'Période de Saisie',
                'verbose_name_plural': 'Périodes de Saisie',
                'db_table': 'periodes_saisie',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_cc',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_sn',
        ),
        migrations.RemoveField(
            model_name='note',
            name='semestre',
        ),
    ]
