# Generated by Django 4.2.9 on 2026-07-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_enseignants', '0003_alter_note_unique_together_note_note_cc1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi')], max_length=3)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=50, null=True)),
                ('annee_academique', models.CharField(default='2024-2025', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='app_enseignants.enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='app_enseignants.filiere')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='app_enseignants.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='app_enseignants.niveau')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='app_enseignants.specialite')),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Emploi du temps',
                'db_table': 'emplois_du_temps',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
    ]
