apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: univora
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 10.0.2.15:5000/univora-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: univora-config
                  key: VITE_API_BASE
